---
title: "IMR Acoustic Survey Data"
author: "Janelle Morano"
date: "2/17/2020"
output: html_document
---
## Summary of Data
Acoustic survey data from Norwegian Institute of Marine Science in the Barents Sea, 2004-2013. Data acquired from Pat Sullivan. **Missing metadata.**

* polar_cod
* herring
* capelin
* saithe
* redfish
* haddock_cod
* haddock
* cod
* blue_whiting
* Norway_pout
* other
* plankton
* zero_group_fish
* total

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
data = read.csv("AllData.csv", head = TRUE)
head(data)
#zero-group fish are immature capelin
dim(data) 
(iyear = unique(data$year))
```

```{r allfish, include = FALSE}
## AVERAGE species by year
#average COD by year
#tapply(cod, year, mean)
ave.cod<-tapply(data$cod, data$year, mean)

#average CAPELIN by year
ave.capelin<-tapply(data$capelin, data$year, mean)

#average POLAR COD by year
#tapply(polar_cod, year, mean)
ave.polar_cod<-tapply(data$polar_cod, data$year, mean)

#average HERRING by year
ave.herring<-tapply(data$herring, data$year, mean)

#average SAITHE by year
ave.saithe<-tapply(data$saithe, data$year, mean)

#average REDFISH by year
ave.redfish<-tapply(data$redfish, data$year, mean)

#average HADDOCK_COD by year
ave.haddock_cod<-tapply(data$haddock_cod, data$year, mean)

#average HADDOCK by year
ave.haddock<-tapply(data$haddock, data$year, mean)

#average BLUE WHITING by year
ave.blue_whiting<-tapply(data$blue_whiting, data$year, mean)

#average NORWAY POUT by year
ave.norway_pout<-tapply(data$Norway_pout, data$year, mean)

#average PLANKTON by year
#no data for plankton
#ave.plankton<-tapply(data$plankton, data$year, mean)

#average ZERO GROUP FISH by year
ave.zero_group_fish<-tapply(data$zero_group_fish, data$year, mean)

```

```{r allfish_graph, echo = FALSE}
## Simple graph of all of the species
plot(iyear, ave.capelin,type = "o", lty = 1, col = "blue", xlab = "Year", ylab = "Fish (unknown unit)")
lines(iyear, ave.cod, type = "o", lty = 1, col = "darkgreen")
lines(iyear, ave.herring, type = "o", lty = 1, col = "lightblue")
lines(iyear, ave.haddock, type = "o", lty = 1, col = "green")
#lines(iyear, ave.redfish, type = "o", lty = 1, col = "red")
lines(iyear, ave.polar_cod, type = "o", lty = 1, col = "purple")
#lines(iyear, ave.saithe, type = "o", lty = 1, col = "red")
#lines(iyear, ave.haddock_cod, type = "o", lty = 1, col = "red")
#lines(iyear, ave.blue_whiting, type = "o", lty = 1, col = "red")
#lines(iyear, ave.norway_pout, type = "o", lty = 1, col = "red")
lines(iyear, ave.zero_group_fish, type = "o", lty = 1, col = "red")
legend("topleft", legend=c("capelin", "cod", "herring", "haddock", "polar cod", 'zero group fish'),
       col=c("blue", "darkgreen", "lightblue", "green", "purple", "red"), lty=1, cex=1)
```
