# Ch4- Linear Regression

#Linear Regression, using priors
n <- 10 #samples
alpha <- rnorm(n, 60, 10) #average adult weight
beta <- rlnorm(n, 0, 10) #slope, kg per centimeter, but when beta = rnorm(n, 0, 10), it's symeteric around 0 which is biologically wrong (you typically don't get lighter as you get taller)

Hbar <- 150 #mean height
Hseq <- seq(from=130, to =170, len=30) #samples of adult heights

plot(NULL, xlim=c(130, 170), #limits are the sample measurements
     ylim=c(10,100), #lmits
     xlab = "height (cm)",
     ylab="weight (kg)")
for (i in 1:n)
  lines( Hseq, 
         alpha[i] + beta[i] *(Hseq-Hbar), 
         lwd=3, col=2)


# set.seed(5)
# create random numbers that are the same. Random numbers are pseudorandomly created because they are generated by an algorithm, so if you use set.seed, you can generate the same string of numbers in a reproducible way. 

# Validate
alpha <- 70
beta <- 0.5 #slope
sigma <- 5
n_individuals <- 100
H <- runif(n_individuals, 130, 170)
mu <- alpha + beta * (H-mean(H))
W <- rnorm(n_individuals, mu, sigma)

dat <- list( H=H, W=W, Hbar=mean(H))

m_validate <- quap(  #quadratic approximation
  alist(
    W ~ dnorm(mu, sigma),
    mu <- a + b * (H-Hbar),
    a ~ dnorm(60, 10),
    b ~ dlnorm(0,1),
    sigma ~ dunif(0,10)
  ), data = dat)
